version: '3.1'

services:
  mongo:
    container_name: mongo_db
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    environment:
        - "MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}"
        - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}"
        - "MONGO_INITDB_DATABASE=${MONGO_DATABASE}"
    volumes:
      - database:/data/db
    env_file:
      - .env

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"

volumes:
    database: